### PR TITLE
docs: add minor fixes after review

### PR DESCRIPTION
**Pull request by janderssonse**
This PR aims to fix a few minor topics after a review from Foundation for Public Code.
It is part of an ongoing process to improve the project.

Aims to fix the following doc content:
- Closer explain the connection to Digg's Internal Open Source Policy and how they are connected. (This project can be seen as a practical appendix from that.
- Adds a "Public known users list"
- Adds a note in Contributing that maintanance and review costs might at times have to be agreed upon, and gives some examples for when that might occur.
- Adds a note about expected response times.

Structure:
- The SECURITY.md template was moved to SECURITY.template.md, and a real SECURITY, based on that for this project was added.
- Same with CONTRIBUTING, a template version was added.
- The Standard moved to the CONTRIBUTING file

## Checklist

- [x] My contributions and commit messages follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [x] The Pull Request has an informative and human-readable title
- [x] Changes are limited to a single goal (avoid scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] I confirm that I have read any Contribution guidelines (CONTRIBUTING)
- [x] I confirm that I wrote and/or have the right to submit the contents of my PR, by agreeing to the _Developer Certificate of Origin_, by adding a 'sign-off' to my commits

### CODE REVIEW

**Comment by janderssonse** [comment]
@danneleaf Note: Linting and license errors are fixed in a seperate PR, with the addition of familiar Code Quality Script.:) . (The code quality script PR with changes is here, https://github.com/diggsweden/open-source-project-template/pull/7 but we should merge this first).

But, Dont merge this, please just have a look at the changes and if you basically agree. We''ll have plenty of time to improve the texts in further reviews, I just took the low hanging fruits here.

**Review by danneleaf — APPROVED** [review]
It looks good! 👍

**Comment by Ayko1595** [comment]
This looks good! 👍🏻

**Review by Ayko1595 — APPROVED** [review]

**Comment by janderssonse** [comment]
Thanks from both, I'll merge this and the other one hanging. I'll involve you both more the coming rounds for this take, and I'm looking forward to introduce @danneleaf and @Ayko1595 to each other at soon to be meeting.:)

**Pull request merged**
