### PR TITLE
docs: add basic governance files

### PR DESCRIPTION
**Pull request by janderssonse**
Adds a GOVERNANCE-template, a Swedish version of the template and a project.
It is really a low key GOVERNANCE-file, as a general reminder that governance is considered rather than a full blown example for a major project.

## Checklist

- [x] My contributions and commit messages follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes
- [x] The Pull Request has an informative and human-readable title
- [x] Changes are limited to a single goal (avoid scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] I confirm that I have read any Contribution guidelines (CONTRIBUTING)
- [x] I confirm that I wrote and/or have the right to submit the contents of my PR, by agreeing to the _Developer Certificate of Origin_, by adding a 'sign-off' to my commits

### CODE REVIEW

**Comment by janderssonse** [comment]
@danneleaf I think you would need to add your digg-email to your github-user account if you want to get any creds as co-author for this and a few earlier ones.

**Comment by danneleaf** [comment]
@janderssonse Thanks for pointing that out, I have added my digg mail now! :)

**Comment by janderssonse** [comment]
> @janderssonse Thanks for pointing that out, I have added my digg mail now! :)

And,, I can see you got cred now!

**Review by danneleaf — APPROVED** [review]
Looks good, seems like you added everything from our discussions :)

**Pull request merged**
