### PR TITLE
docs: update standard for public code assessment

### PR DESCRIPTION
**Pull request by Ainali**
## Description

This contains the assessment as performed by Jan Ainali and Eric Herman towards the Standard for Public Code version 0.7.1 as of the previous commit.

## Checklist

- [x] My contributions and commit messages follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes
- [x] The Pull Request has an informative and human-readable title
- [x] Changes are limited to a single goal (avoid scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] I confirm that I have read any Contribution guidelines (CONTRIBUTING)
- [x] I confirm that I wrote and/or have the right to submit the contents of my PR, by agreeing to the _Developer Certificate of Origin_, by adding a 'sign-off' to my commits

### CODE REVIEW

**Comment by janderssonse** [comment]
Thanks, @Ainali I think you will have github know about your gmail pub key (so that you are a verified user)

**Comment by Ainali** [comment]
> Thanks, @Ainali I think you will have github know about your gmail pub key (so that you are a verified user)

Oh, thanks for the reminder I should fix that. Is this a blocker for the contribution? If so, perhaps clarify that in the CONTRIBUTING file, as it seemed to be optional when I read it.

**Comment by janderssonse** [comment]
Thanks will do. You are most likely correct, it was optional in the text, but as a must in the linters so there is currently a mismatch.

**Review by janderssonse — APPROVED** [review]
Looks good to me!.

**Comment by janderssonse** [comment]
Merged in https://github.com/diggsweden/open-source-project-template/commit/f5be1a5988b10d09d0360247f23a9c5d606556c8. We'll fix the contributor thingie before next round.

**Comment by janderssonse** [comment]
So closing this thanks!

**Pull request closed without merging**
